# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
appName: app-02
appNameGeneric: app-02
configmapPath: "../apps/app-02/configmap.yaml"  # Updated path


image:
  repository: hmsvigle/nginx
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: "02"

service:
  type: ClusterIP
  port: 80
